### ISSUE TITLE
I can't use where condition in the select query

### ISSUE THREAD

**Issue by jeevaraj16** [brody2consult/cordova-sqlite-storage#584]
I have create the table and i insert data successfully in windows phone 8.1. Then i am using where condition to retrieve the but it doesn't work for me. With out where condition is working correctly. 

SELECT * FROM TABLENAME WEHRE COLUMN_NAME='VALUE' 

this is the query i have used in my code. Pls help me to find the solution.

**Comment by brody2consult** [comment]
There is a misspelling in the WHERE keyword.

**Comment by jeevaraj16** [comment]
thank you.. i have corrected it but even it was not working..
 I have used cordova-plugin-sqlite-fts plugin for windows.. because Cordova-sqlite-storage is not working for my windows mobile. I have build the app using phonegap...

SELECT \* FROM TABLENAME WHERE COLUMN_NAME="value";

Is the query is right or not?.. please give me the right solution..

**Comment by brody2consult** [comment]
Please post a full test program to demonstrate your issue.

In general I do not support third-party forks. They tend to go out of date among other things. The `wp8` platform is supported in the Cordova-sqlite-legacy-build-support version for those who need it. If that does not solve your problem please give some more information and I can help resolve it.

**Comment by jeevaraj16** [comment]
Here is my sample code....

`<script>
var db = '';
var cropId = '';
function onLoad(){
    document.addEventListener("deviceready", onDeviceReady, false);
}
function onDeviceReady(){
    db = window.sqlitePlugin.openDatabase({name: "demo.db"});
    db.transaction(queryDB, errorCB, successCB);
}
function queryDB(tx){
    tx.executeSql('SELECT * FROM DEMO WHERE STATUS="true"',[],successDB,errorCB);
}
function successDB(tx,result){
    var length = result.rows.length;
    alert("len = "+length);
}
function errorCB(){
        alert(error.code);
}
</script>`

[code.txt](https://github.com/litehelpers/Cordova-sqlite-storage/files/597211/code.txt)

In this code i have used where condition but it doesn't works for me....
